"""pic

Revision ID: 54efdfb0a523
Revises: 849daec76ece
Create Date: 2020-05-16 02:46:44.432769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54efdfb0a523'
down_revision = '849daec76ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant', sa.Column('email_address', sa.String(length=80), nullable=False))
    op.drop_column('assistant', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant', sa.Column('email', sa.VARCHAR(length=80), nullable=False))
    op.drop_column('assistant', 'email_address')
    # ### end Alembic commands ###
